# If there is no error raised the program will not undergo with the  `try except` block then the `else` will excecute

x=5

try:
    print(x)
except:
    print("Varible is not declared")
else:
    print("No errors in the code")
